### PR TITLE
Added donations endpoint to return donation addresses from the zcashd…

### PR DESCRIPTION
**Pull request by benzcash**
By default, return json for the donation addresses.

Please review that this is a sane method to determine "good" addresses, and they are the appropriate type.

### CODE REVIEW

**Comment by charlieok** [comment]
I've read through this and I think I get what it's doing, but I don't have the context to know whether this is a good method.

Wondering: are 'zt' addresses specifically a testnet thing, applicable to TAZ and not ZEC?

**Review by mdr0id — APPROVED** [review]
ACK.

Background on this is to provide addresses for the smoke-test.py in zcash, to call into for CI. For releases, it fits nicely into a leftover funds (TAZ) component. It should give us some interesting data as we automate more things.

**Comment by mdr0id** [comment]
@charlieok I believe so, see https://zcash.readthedocs.io/en/latest/rtd_pages/addresses.html for more details. IIRC, `zs` is mainnet prefix for z-sap-addr

**Comment by benzcash** [comment]
Yeah, I don't imagine we'll be deploying a mainnet faucet :smile:

**Review by charlieok — APPROVED** [review]
ACK

**Pull request merged**
